import { motion } from 'framer-motion';
import { FiArrowRight, FiCheck, FiMessageCircle, FiShield, FiUsers } from 'react-icons/fi';
import { useNavigate } from 'react-router-dom';

export default function Home() {
  const navigate = useNavigate();
  return <main className="noise min-h-screen overflow-hidden auth-bg">
    <nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-6"><div className="display text-xl font-bold tracking-tight">talksy<span className="gradient-text">.</span></div><div className="flex items-center gap-3"><button onClick={()=>navigate('/login')} className="rounded-full px-4 py-2 text-sm text-white/70 hover:text-white">Log in</button><button onClick={()=>navigate('/register')} className="rounded-full bg-white px-5 py-2.5 text-sm font-semibold text-[#17151d] hover:bg-[#d9fff7]">Get started <FiArrowRight className="ml-1 inline" /></button></div></nav>
    <section className="mx-auto grid max-w-6xl items-center gap-14 px-6 pb-20 pt-16 lg:grid-cols-[1.05fr_.95fr] lg:pt-24"><div><p className="mb-6 flex items-center gap-2 text-sm font-semibold uppercase tracking-[.2em] text-[#70d7c6]"><span className="h-2 w-2 rounded-full bg-[#70d7c6]" /> A calmer way to connect</p><h1 className="display max-w-2xl text-5xl font-semibold leading-[1.05] tracking-[-.04em] sm:text-7xl">Good conversations,<br /><span className="gradient-text">beautifully simple.</span></h1><p className="mt-7 max-w-lg text-lg leading-8 text-white/55">Talksy brings your people into one warm, focused space. No noise. No performance. Just the messages that matter.</p><div className="mt-9 flex flex-wrap gap-3"><button onClick={()=>navigate('/register')} className="rounded-full bg-[#8b7bff] px-6 py-3.5 font-semibold text-white shadow-lg shadow-[#8b7bff]/20 hover:bg-[#9b8eff]">Create your space <FiArrowRight className="ml-2 inline" /></button><button onClick={()=>navigate('/login')} className="rounded-full border border-white/15 px-6 py-3.5 font-semibold text-white/80 hover:bg-white/5">I have an account</button></div><div className="mt-10 flex flex-wrap gap-x-6 gap-y-2 text-sm text-white/45">{['Private by design','Real-time delivery','Free to start'].map(x=><span key={x}><FiCheck className="mr-1 inline text-[#70d7c6]" />{x}</span>)}</div></div><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.7}} className="glass relative rounded-[2rem] p-4 shadow-2xl shadow-black/30"><div className="rounded-[1.5rem] bg-[#17181f] p-5"><div className="mb-8 flex items-center justify-between"><div><p className="font-semibold">Good morning, Alex</p><p className="mt-1 text-xs text-white/40">Your conversations are waiting</p></div><div className="flex h-10 w-10 items-center justify-center rounded-full bg-[#8b7bff] font-bold">A</div></div><div className="space-y-3">{[['Maya Chen','The new photos are incredible ✨','MC','#e7a4b5'],['Studio team','Sprint notes · 4 new messages','ST','#70d7c6'],['Noah Williams','See you around 7?','NW','#8b7bff']].map(([name,msg,ini,color],i)=><div key={name} className={`flex items-center gap-3 rounded-2xl p-3 ${i===0?'bg-white/8':'bg-white/[.025]'}`}><div style={{background:color}} className="flex h-11 w-11 items-center justify-center rounded-full text-sm font-bold text-[#17181f]">{ini}</div><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{name}</p><p className="truncate text-xs text-white/45">{msg}</p></div><span className="text-[10px] text-white/30">{i===0?'now':i===1?'2m':'1h'}</span></div>)}</div><div className="mt-5 flex items-center gap-3 rounded-2xl border border-white/8 bg-white/[.025] p-3"><div className="h-2 w-2 rounded-full bg-[#70d7c6]" /><span className="text-xs text-white/45">Maya is typing...</span></div></div></motion.div></section>
    <section className="mx-auto grid max-w-6xl gap-4 px-6 pb-20 sm:grid-cols-3">{[[FiMessageCircle,'Made for the moment','Fast, focused messaging that stays out of your way.'],[FiUsers,'Your people, together','Find friends and start a conversation in seconds.'],[FiShield,'A little more private','Your space is yours. Always.']].map(([Icon,title,copy])=><div key={title} className="glass rounded-3xl p-6"><Icon className="mb-8 text-2xl text-[#70d7c6]" /><h3 className="display text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-white/45">{copy}</p></div>)}</section>
  </main>;
}
